apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc_deploy
  labels:
    app: abc_deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc_deploy
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc-app
        image: vijay1453/abc_tech:latest
        ports:
        - containerPort: 9090  # Updated to match the Dockerfile

---

apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app: abc_deploy
  ports:
    - protocol: TCP
      port: 80            	 # External service port
      targetPort: 9090     	 # Updated to match containerPort
      nodePort: 30000-32767  # NodePort, within the valid range
  type: NodePort          	 # Correct indentation for the NodePort service type

