apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deploy  # Changed from abc_deploy to abc-deploy
  labels:
    app: abc-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-deploy
  template:
    metadata:
      labels:
        app: abc-deploy
    spec:
      containers:
      - name: abc-app
        image: vijay1453/abc_tech:latest
        ports:
        - containerPort: 9090  # Match this with the port in your Dockerfile

---

apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app: abc-deploy  # Updated to match the deployment name
  ports:
    - protocol: TCP
      port: 80                   # External service port
      targetPort: 9090           # Match containerPort
      nodePort: 30000            # NodePort
  type: NodePort
