# app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deploy
  labels:
    app: abc-deploy  # Label applied to deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-deploy  # Pods will have this label
  template:
    metadata:
      labels:
        app: abc-deploy  # Pods inherit this label
    spec:
      containers:
      - name: abc-app
        image: vijay1453/abc_tech:latest
        ports:
        - containerPort: 9090  # Match the exposed port

---

apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app: abc-deploy  # This must match the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30000
  type: NodePort
