apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcapp
  labels:
    app: abcapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abcapp
  template:
    metadata:
      labels:
        app: abcapp
    spec:
      containers:
      - name: abcapp
        image: vijay1453/abcapp:latest
        ports:
        - containerPort: 9090  # The port your application listens on

---

apiVersion: v1
kind: Service
metadata:
  name: abcapp-service
spec:
  selector:
    app: abcapp
  ports:
    - protocol: TCP
      port: 80                # External service port
      targetPort: 9090        # The port the application listens on in the container
      nodePort: 30000         # NodePort, accessible on each node
  type: NodePort              # Expose the service as a NodePort
